version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./app:/var/www/html  